pod 'RESideMenu', '~> 4.0.7'
pod 'EstimoteSDK'
pod 'AMScrollingNavbar'
pod 'SVProgressHUD'
pod 'INTULocationManager'
pod 'VBFPopFlatButton'
pod 'AutoScrollLabel'
pod 'YXTMotionView' , :git => 'https://github.com/hanton/YXTMotionView'
